### ISSUE TITLE
Possibility to Restore Data from PV

### ISSUE THREAD

**Issue by Valon-WSP-Soft** [arangodb/kube-arangodb#1270]
We run a ArangoDB development cluster on k8s with the local storage like explained in the docs [Storage Docs](https://www.arangodb.com/docs/stable/deployment-kubernetes-storage-resource.html).

Unfortunately, our k8s cluster crashed and we lost the _arangoDeployment_. We managed to rescue the local files from the PV of each agent and **dbserver**.

However, when we copy these files to PVs in a new _arangoDeployment_ the coordinators stop working.
According to the error message, the **coordinators cannot connect** to a _dbserver_ that is not part of the current _arangoDeployment_. We assume it was part of the previously lost _arangoDeployment_.

**Is there a possibility to somehow restore the data? Maybe by excluding some files from the copy?** 

### Error-Logs:
```
2023-03-09T21:59:45Z [1] DEBUG [f3533] {general} ArangoError 1465: AQL: cluster internal HTTP connection broken (while optimizing plan)
2023-03-09T21:59:45Z [1] DEBUG [f3533] {general}     at ArangoStatement.execute (/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js:84:16)
2023-03-09T21:59:45Z [1] DEBUG [f3533] {general}     at ArangoDatabase._query (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:102:45)
2023-03-09T21:59:45Z [1] DEBUG [f3533] {general}     at selfHeal (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:160:33)
2023-03-09T21:59:45Z [1] DEBUG [f3533] {general}     at Object.selfHealAll [as healAll] (/usr/share/arangodb3/js/server/modules/@arangodb/foxx/manager.js:120:20)
2023-03-09T21:59:45Z [1] DEBUG [f3533] {general}     at eval (eval at <anonymous> (unknown source), <anonymous>:3:23)
2023-03-09T21:59:45Z [1] DEBUG [f3533] {general}     at eval (eval at <anonymous> (unknown source), <anonymous>:4:11)
2023-03-09T21:59:45Z [1] DEBUG [f3533] {general}     at eval (eval at <anonymous> (unknown source), <anonymous>:4:23)
2023-03-09T21:59:48Z [1] ERROR [abcde] {communication} communication error: 'Unable to connect' from destination 'server:PRMR-l1pp19yl', url: POST /_api/aql/setup
```

**Comment by joerg84** [comment]
It sounds like the central k8s metadata is missing (CR), please make sure to have backups of the other PVs (which you seemingly have done). Let me reach out to the k8s team and ask for options available here. Can you ping me either on the community slack or email joerg at arangodb dot com).

**Comment by Valon-WSP-Soft** [comment]
Recovered the data it with this tutorial: https://github.com/arangodb/kube-arangodb/blob/GT-390_recovery_doc/docs/design/recovery.md

Thanks to the arangoDB Team for the support!
